name: DeployToServer

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-20.04

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: will-be-added-in-next-step

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H 45.67.59.38 >> ~/.ssh/known_hosts
      - run: ssh root@45.67.59.38
      - name: Deploy through SSH with rsync
        run: |
          rsync -avz ./dist rms_server:/home/metradl/RMS/actions-test
